# Generated by Django 5.1.1 on 2024-10-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
