SELECT ?item ?itemLabel ?league_systemLabel ?level ?league_countryLabel
WHERE {   
  ?item wdt:P31 wd:Q15991303. 
  ?item p:P361 ?statement.   
  ?statement ps:P361 ?league_system;
             pq:P3983 ?level.
  ?league_system wdt:P17 ?league_country.
  ?pq_qual wikibase:qualifier pq:P3983.  
  
  
  # Filter for levels 1, 2, or 3
  FILTER(?level IN (1, 2, 3))
  
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}

ORDER BY ?league_systemLabel ?level