# Generated by Django 5.1.1 on 2024-10-14 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kit_type', models.CharField(max_length=10)),
                ('season', models.IntegerField(blank=True, null=True)),
                ('sponsor', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'kit',
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('league_name', models.CharField(max_length=100)),
                ('level', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'league',
            },
        ),
        migrations.CreateModel(
            name='KitColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(max_length=15)),
                ('red', models.IntegerField()),
                ('green', models.IntegerField()),
                ('blue', models.IntegerField()),
                ('kit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.kit')),
            ],
            options={
                'db_table': 'kitcolor',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('wiki_link', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.league')),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.AddField(
            model_name='kit',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.team'),
        ),
    ]
