# Generated by Django 5.1.1 on 2024-10-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_league_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kit',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='kitcolor',
            name='part',
        ),
        migrations.AddField(
            model_name='kit',
            name='image',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kit',
            name='kit_part',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
