# Generated by Django 5.1.1 on 2024-10-17 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_kit_slug_remove_kitcolor_part_kit_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kit',
            name='image',
        ),
        migrations.RemoveField(
            model_name='kit',
            name='kit_part',
        ),
        migrations.AlterField(
            model_name='kit',
            name='season',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.CreateModel(
            name='KitPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kit_part', models.CharField(blank=True, max_length=10, null=True)),
                ('image', models.CharField(blank=True, max_length=50, null=True)),
                ('background_color', models.CharField(default=None, max_length=7)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.kit')),
            ],
            options={
                'db_table': 'kit_part',
            },
        ),
        migrations.CreateModel(
            name='KitPartColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default=None, max_length=7)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.kitpart')),
            ],
            options={
                'db_table': 'kit_part_color',
            },
        ),
        migrations.DeleteModel(
            name='KitColor',
        ),
    ]
