# Generated by Django 5.1.1 on 2024-10-17 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_kit_image_remove_kit_kit_part_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kitpart',
            old_name='image',
            new_name='image_name',
        ),
    ]
