# Generated by Django 5.1.1 on 2024-11-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_userkitlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userkitlog',
            name='kit',
        ),
        migrations.AddField(
            model_name='userkitlog',
            name='kit_type',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userkitlog',
            name='season',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
